name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Login
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: bottlepy
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: docker build . --tag docker.pkg.github.com/bottlepy/test-docker/testenv:latest
    - name: Push
      run: docker push docker.pkg.github.com/bottlepy/test-docker/testenv:latest
